name: charusatsocial
description: CharusatSocial

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.7
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  firebase_crashlytics: '2.5.3'
  firebase_database: ^9.1.4
  firebase_dynamic_links: ^4.3.11
  image_picker: ^0.8.5+3
  google_fonts: ^4.0.1
  path_provider: ^2.0.11
  video_player: ^2.4.6
  intl: ^0.17.0
  timeago: ^3.3.0
  agora_rtc_engine: ^5.3.0
  permission_handler: ^9.2.0
  auto_size_text: ^3.0.0
  uuid: ^3.0.6
  share: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  in_app_review: ^2.0.4
  url_launcher: ^6.1.5
  html: ^0.15.0
  http: ^0.13.5
  flutter_lints: ^2.0.1
  flutter_markdown: ^0.6.10+3
  video_compress: ^3.1.1
  cached_network_image: ^3.2.1
  wakelock: ^0.6.2
  build_runner: ^2.2.1
  build_web_compilers: ^3.2.6
  change_app_package_name: ^1.1.0
  firebase_core_platform_interface: 4.5.1
  cloud_firestore_platform_interface: any
  firebase_auth_platform_interface: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

